---
- name: git config name
  shell: git config --global user.name "{{git.name}}" executable=/bin/bash
  tags:
    - deploy

- name: git config email
  shell: git config --global user.email {{git.email}} executable=/bin/bash
  tags:
    - deploy

- name: copy /.ssh/config
  copy: src=ssh_config dest=/home/{{ deploy_user }}/.ssh/config
  tags:
    - deploy

- name: pull git
  git: repo={{git.repo}} dest={{code_root_dir}}
  tags:
    - deploy

- name: "ensure ~/.virtualenvs/{{project_name}} dir is created"
  file: path=/home/{{deploy_user}}/.virtualenvs/{{project_name}} state=directory
  tags:
    - deploy

- name: "ensure correct permission in /var/log/{{project_name}}"
  command: "{{ item }}"
  with_items:
    - "chown --recursive deploy:www-data /var/log/{{project_name}}"
    - "chmod --recursive 775 /var/log/{{project_name}}"
  tags:
    - deploy

- name: install pip requirements
  pip: >
    virtualenv=/home/{{deploy_user}}/.virtualenvs/{{project_name}}
    requirements={{code_root_dir}}/{{reqs_dir}}/{{settings_module}}.txt
  tags:
    - deploy

- name: run syncdb
  django_manage: >
    app_path={{code_root_dir}} command={{item}} settings=remindr.settings.prod
    virtualenv=/home/{{deploy_user}}/.virtualenvs/{{project_name}}
  with_items:
    - syncdb
    - migrate
    - collectstatic
  tags:
    - deploy
  environment:
    ENV_VAR_NAME: ENV_VALUE

- name: "ensure {{project_name}} uwsgi is running"
  supervisorctl: name={{project_name}} state=restarted
  sudo: True
  tags:
    - deploy

- name: ensure celerybeat is running
  supervisorctl: name=celerybeat state=restarted
  sudo: True
  tags:
    - deploy

- name: ensure celeryd is running
  supervisorctl: name=celeryd state=restarted
  sudo: True
  tags:
    - deploy
