---
common:
  locale: en_US.UTF-8
  deploy_username: deploy
  ubuntu_release: precise
  logwatch_email: ops@releasly.com
  deploy_password: '6AQZI1Z95b53U'
  # crypted password, generated on a Linux box using: echo 'import crypt,getpass; print crypt.crypt(getpass.getpass(), "?6+AC3bdCF7!")' | python -
  ssh_users:
    - deploy
    - vagrant
  pkg:
    - python-software-properties
    - build-essential
    - git-core
    - logwatch
    - postfix
    - unattended-upgrades
    - fail2ban
postfix:
  root_address: ops@releasly.com
  mailname: releasly.com
