---
- name: restart postgresql
  service: name=postgresql state=restarted
  tags:
    - postgres

- name: restart Redis
  service: name={{redis.service}} state=restarted
  tags:
    - redis

- name: restart Redmon
  service: name={{redmon.service}} state=restarted
  tags:
    - redis
