---
- name: add nginx ppa
  apt_repository: repo=ppa:nginx/stable state=present update_cache=yes
  tags:
    - nginx

- name: install nginx package
  apt: pkg=nginx state=latest update_cache=yes cache_valid_time={{six_hours}}
  sudo: True
  tags:
    - nginx

- name: remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  tags:
    - nginx

# - name: write nginx.conf
#   template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf
#   tags:
#     - nginx
