---
- name: add deployment user
  user: name={{setup.deploy_username}} password={{setup.deploy_password}} shell=/bin/bash uid=1002 groups=www-data append=yes createhome=yes state=present
  tags:
    - setup

- name: add deployment user to sudoers
  lineinfile: dest=/etc/sudoers regexp="{{setup.deploy_username}} ALL" line="{{setup.deploy_username}} ALL=(ALL) ALL" state=present
  tags:
    - setup

- name: "add ssh key for: {{setup.deploy_username}}"
  authorized_key: user={{setup.deploy_username}} key="{{ lookup('file', '~/.ssh/v.pub') }}"
  tags:
    - setup

- name: write .bash_aliases
  template: src=bash_aliases dest=/home/{{setup.deploy_username}}/.bash_aliases owner={{setup.deploy_username}} group=www-data
  tags:
    - setup

- name: write .bashrc
  copy: src=bashrc dest=/home/{{setup.deploy_username}}/.bashrc owner={{setup.deploy_username}} group=www-data
  tags:
    - setup

- name: install web packages
  apt: pkg={{item}} state=installed update_cache=yes cache_valid_time={{six_hours}}
  with_items: "{{setup.pkg}}"
  tags:
    - setup

- name: "create /var/log/{{project_name}} directory"
  file: path=/var/log/{{project_name}} owner={{deploy_user}} group=www-data state=directory mode=775
  tags:
    - setup
