---
- name: add deployment user
  user: name={{deploy_user}} password={{deploy_pass}} shell=/bin/bash uid=1002 groups=www-data append=yes createhome=yes state=present
  tags:
    - setup

- name: add deployment user to sudoers
  lineinfile: dest=/etc/sudoers regexp="{{deploy_user}} ALL" line="{{deploy_user}} ALL=(ALL) ALL" state=present
  tags:
    - setup

- name: copy ssh key over
  copy: src=keys/key.pub dest=/home/{{deploy_user}}/.ssh/id_rsa.pub mode=644
  tags:
    - setup

- name: "add ssh key for: {{deploy_user}}"
  authorized_key: user={{ deploy_user }} key="{{ item }}"
  with_file:
    - ../../../keys/key.pub
  tags:
    - setup

- name: write .bash_aliases
  template: src=bash_aliases dest=/home/{{deploy_user}}/.bash_aliases owner={{deploy_user}} group=www-data
  tags:
    - setup

- name: write .bashrc
  copy: src=bashrc dest=/home/{{deploy_user}}/.bashrc owner={{deploy_user}} group=www-data
  tags:
    - setup

- name: install web packages
  apt: pkg={{item}} state=installed update_cache=yes cache_valid_time={{six_hours}}
  with_items: "{{setup.pkg}}"
  tags:
    - setup

- name: "create /var/log/{{project_name}} directory"
  file: path=/var/log/{{project_name}} owner={{deploy_user}} group=www-data state=directory mode=775
  tags:
    - setup
