---
- name: add deployment user
  user: name={{setup.deploy_username}} password={{setup.deploy_password}} shell=/bin/bash group=www-data append=yes createhome=yes state=present
  tags:
    - setup

- name: add deployment user to sudoers
  lineinfile: dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present
  tags:
    - setup

- name: "add ssh key for: {{setup.deploy_username}}"
  authorized_key: user={{setup.deploy_username}} key="{{ lookup('file', '~/.ssh/v.pub') }}"
  tags:
    - setup

- name: install web packages
  apt: pkg={{item}} state=installed update_cache=yes cache_valid_time={{six_hours}}
  with_items: "{{setup.pkg}}"
  tags:
    - setup
