---
- name: add deployment user
  user: name={{setup.deploy_username}} password={{setup.deploy_password}}
  tags:
    - setup

- name: add deployment user to sudoers
  lineinfile: dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present
  tags:
    - setup

- name: "add ssh key for: {{setup.deploy_username}}"
  authorized_key: user={{setup.deploy_username}} key="{{ lookup('file', '~/.ssh/v.pub') }}"
  tags:
    - setup
