---
postgres:
  packages:
    - libpq-dev
    - postgresql-9.3
    - postgresql-contrib-9.3
redis:
  package: 'redis-server'
  service: 'redis-server'
redmon:
  service: 'redmon'
  dependencies:
    - ruby1.9.3
    - rubygems
    - g++
  gems:
    - bundler
    - redmon
